name: Build & Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [v12.22.1]

    steps:
      - uses: actions/checkout@v2
      - name: Deploy Bixie server
        uses: actions/setup-node@v2
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  
  build:
    needs: test

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        name: bixie
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: malukimuthusi/bixie
        tags: "latest"